'use client'
import { createContext, useContext, useState, useEffect } from 'react'

export type Lang = 'en' | 'fr'

// ── All UI strings ─────────────────────────────────────────────────────────────
const T = {
  en: {
    // Nav
    nav_navigate:    'Navigate',
    nav_dashboard:   'Dashboard',
    nav_board:       'Board',
    nav_table:       'Table',
    nav_approved:    'Approved',
    nav_samples:     'Samples',
    nav_team:        'Team',
    nav_profile:     'Profile',
    nav_templates:   'Templates',
    nav_settings:    'Settings',
    nav_newRecord:   '+ New Record',
    nav_signOut:     'Out',

    // Record Drawer
    drawer_details:       'Details',
    drawer_comments:      'Comments',
    drawer_history:       'History',
    drawer_edit:          '✏️ Edit',
    drawer_notify:        '✉ Notify',
    drawer_archive:       '📁 Archive',
    drawer_restore:       '📤 Restore',
    drawer_archived:      '📁 Archived',
    drawer_moveStage:     'MOVE STAGE',
    drawer_priority:      'PRIORITY',
    drawer_waitingOn:     'Waiting on:',
    drawer_notes:         'NOTES',
    drawer_feedback:      'LICENSOR FEEDBACK',
    drawer_attachments:   'ATTACHMENTS',
    drawer_upload:        '+ Upload',
    drawer_uploading:     'Uploading…',
    drawer_cover:         'COVER',
    drawer_setCover:      '⭐ Cover',
    drawer_open:          'Open ↗',
    drawer_addComment:    'Add a comment…',
    drawer_post:          'Post',
    drawer_noComments:    'No comments yet.',
    drawer_noHistory:     'No history yet.',
    drawer_brand:         'Brand',
    drawer_property:      'Property',
    drawer_productType:   'Product Type',
    drawer_gender:        'Gender',
    drawer_owner:         'Owner',
    drawer_contact:       'Contact',
    drawer_licensorRef:   'Licensor Ref',
    drawer_samples:       'Samples',
    drawer_submission:    'Submission',
    drawer_conceptApproval: 'Concept Approval',
    drawer_ppsPhotos:     'PPS Photos',
    drawer_ppsApproval:   'PPS Approval',
    drawer_sampleSent:    'Sample Sent',
    drawer_sampleApproval:'Sample Approval',
    drawer_techPack:      'Tech Pack',
    drawer_additionalLink:'Additional Link',
    drawer_deleteConfirm: 'Delete this record? This cannot be undone.',
    drawer_system:        'System',

    // Record Form
    form_internalRef:     'Internal Ref *',
    form_licensorRef:     'Main Licensor Ref',
    form_productName:     'Product Name *',
    form_productType:     'Product Type',
    form_gender:          'Gender',
    form_brand:           'Brand',
    form_property:        'Property',
    form_stage:           'Stage',
    form_priority:        'Priority',
    form_owner:           'Owner',
    form_waitingOn:       'Waiting On',
    form_contact:         'Contact',
    form_nextAction:      'Next Action',
    form_notes:           'Notes',
    form_feedback:        'Licensor Feedback',
    form_techPackLink:    'Tech Pack Link',
    form_additionalLink:  'Additional Link',
    form_submissionDate:  'Submission Date',
    form_samplesQty:      'Samples Qty',
    form_reminder:        '🔔 Follow-up Reminder',
    form_reminderDate:    'Reminder Date',
    form_reminderNote:    'Note (optional)',
    form_reminderDone:    'Mark reminder as done',
    form_unassigned:      '— Unassigned —',
    form_select:          '— Select —',
    form_addBrand:        '＋ Add new brand…',
    form_addProperty:     '＋ Add new property…',
    form_typeBrand:       'Type brand name…',
    form_typeProperty:    'Type property name…',
    form_reminderPlaceholder: 'e.g. Follow up with licensor for approval',
    form_attachClick:     'Click to attach images or files',
    form_attachSub:       'Will upload when record is saved',
    form_attachments:     'ATTACHMENTS',
    form_uploadFile:      '＋ Upload file',
    form_uploading:       'Uploading…',
    form_save:            'Save',
    form_saving:          'Saving…',
    form_cancel:          'Cancel',

    // Dashboard
    dash_activeRecords:   'Active Records',
    dash_fullyApproved:   'Fully Approved',
    dash_remindersDue:    'Reminders Due',
    dash_upcomingWeek:    'upcoming this week',
    dash_noUpcoming:      'No upcoming reminders',
    dash_awaitingLicensor:'Awaiting Licensor',
    dash_awaitingFull:    'awaiting approval',
    dash_overdue:         '🔴 Overdue',
    dash_dueToday:        '🟡 Due Today',
    dash_upcoming:        '🔵 Upcoming (next 7 days)',
    dash_reminders:       '🔔 Reminders',
    dash_pending:         'pending',
    dash_viewAll:         'View all →',
    dash_markDone:        'Mark done',
    dash_pipeline:        'Pipeline Progress',
    dash_records:         'records',
    dash_recentActivity:  'Recent Activity',
    dash_noActivity:      'No recent activity.',

    // Table
    table_img:            'IMG',
    table_ref:            'Ref',
    table_product:        'Product',
    table_type:           'Type',
    table_brand:          'Brand',
    table_property:       'Property',
    table_stage:          'Stage',
    table_priority:       'Priority',
    table_owner:          'Owner',
    table_waiting:        'Waiting',
    table_nextAction:     'Next Action',
    table_samples:        'Samples',
    table_reminder:       'Reminder',
    table_noRecords:      'No records match your filters.',
    table_search:         'Search records…',
    table_allBrands:      'All Brands',
    table_allProperties:  'All Properties',
    table_allStages:      'All Stages',
    table_allOwners:      'All Owners',
    table_allPriorities:  'All Priorities',
    table_waitingOn:      'Waiting On',
    table_showArchived:   'Archived',
    table_showReminders:  'Reminders',
    table_exportCSV:      'Export CSV',
    table_newRecord:      '+ New Record',

    // Settings
    settings_title:       'System Settings',
    settings_subtitle:    'Admin-only controls for automated features.',
    settings_emailAuto:   'Email Automation',
    settings_loading:     'Loading…',
    settings_reminderLabel: 'Daily Reminder Emails',
    settings_reminderHint:  'Send automatic email reminders to record owners at 9:00 AM every day for due or overdue reminders.',
    settings_on:          'On',
    settings_off:         'Off',
    settings_howTitle:    'How it works:',
    settings_howText:     'Every day at 9:00 AM, CodiFlow checks for records with a reminder date that is today or overdue. Each record owner receives an individual email listing the reminder. Turn this off to stop all automated reminder emails.',
    settings_save:        'Save Settings',
    settings_saving:      'Saving…',
    settings_saved:       '✓ Saved!',

    // Dashboard extra
    dash_title:            'Dashboard',
    dash_pipelineByStage:  'Pipeline by Stage',
    dash_byBrand:          'Records by Brand',
    dash_byOwner:          'Records by Owner',
    dash_byPriority:       'By Priority',
    dash_needsAttention:   '⚠️ Needs Attention',
    dash_allUpToDate:      'All records are up to date! ✅',
    dash_noRecords:        'No records yet.',
    dash_nothingBlocked:   'Nothing blocked. ✅',
    dash_followUpReminders:'🔔 Follow-up Reminders',
    dash_urgentHigh:       'Urgent / High Priority',
    dash_urgentCount:      'urgent',
    dash_noUrgent:         'No urgent items',
    dash_archived:         'archived',
    dash_withSamples:      'with samples',
    dash_stale:            'stale',
    dash_waitingOn:        'Waiting On',
    dash_staleTag:         'd stale',

    // Filter bar
    filter_search:         'Search records…',
    filter_clearAll:       'Clear all',
    filter_archived:       'Archived',
    filter_allBrands:      'All Brands',
    filter_allProperties:  'All Properties',
    filter_allStages:      'All Stages',
    filter_allOwners:      'All Owners',
    filter_allPriorities:  'All Priorities',
    filter_allWaiting:     'All Waiting On',
    filter_reminders:      '🔔 Reminders',

    // Approved view
    approved_title:        '🏆 Approved Designs',
    approved_subtitle:     'fully approved · ready for launch',
    approved_export:       '↓ Export CSV',
    approved_licensorRef:  'Licensor Ref',
    approved_product:      'Product',
    approved_brandProp:    'Brand / Property',
    approved_owner:        'Owner',
    approved_samples:      'Samples',
    approved_notes:        'Notes',
    approved_empty:        'No approved designs yet.',

    // Samples view
    samples_title:         '🧪 Sample Requests',
    samples_search:        'Search…',
    samples_count:         'records with samples',
    samples_product:       'Product',
    samples_ref:           'Ref',
    samples_brandProp:     'Brand / Property',
    samples_stage:         'Stage',
    samples_owner:         'Owner',
    samples_nextAction:    'Next Action',
    samples_qty:           'Sample Qty',

    // Templates view
    tmpl_title:            '✉ Email Templates',
    tmpl_subtitle:         'One template per stage',
    tmpl_customActive:     'Custom template active',
    tmpl_subjectLine:      'Subject Line',
    tmpl_subjectPrefix:    'Custom Subject Prefix',
    tmpl_optional:         '(optional)',
    tmpl_preview:          'Preview:',
    tmpl_introMessage:     'Intro Message',
    tmpl_introHint:        'Custom text (appears at the top of the email)',
    tmpl_autoSend:         '⚡ Auto-send Recipients',
    tmpl_selectedCount:    'selected',
    tmpl_autoSendHint:     'Selected users automatically receive this email whenever a record moves to',
    tmpl_noManual:         'No manual action needed.',
    tmpl_noTeam:           'No active team members found.',
    tmpl_willReceive:      'Will receive ✓',
    tmpl_autoNote1:        'user(s) will automatically receive this email on every stage change to',
    tmpl_emailContent:     'Email Content',
    tmpl_emailContentHint: 'Choose which fields to include in the email for this stage.',
    tmpl_productDetails:   '📋 Product Details',
    tmpl_licensorRef:      'Licensor Reference',
    tmpl_licensorRefHint:  "The licensor's own reference number",
    tmpl_productType:      'Product Type',
    tmpl_productTypeHint:  'e.g. Apparel, Accessories',
    tmpl_genderTarget:     'Gender / Target',
    tmpl_genderTargetHint: 'e.g. Unisex, Kids Boys',
    tmpl_contactName:      'Contact Name',
    tmpl_submissionDate:   'Submission Date',
    tmpl_priorityLevel:    'Priority Level',
    tmpl_priorityHint:     'Low / Medium / High / Urgent',
    tmpl_samplesQty:       'Samples Quantity',
    tmpl_workflow:         '⚡ Workflow Status',
    tmpl_waitingOn:        'Waiting On',
    tmpl_waitingOnHint:    'Who is currently blocking progress',
    tmpl_nextAction:       'Next Action',
    tmpl_nextActionHint:   'What needs to happen next',
    tmpl_notesSection:     '📝 Notes & Feedback',
    tmpl_notesSummary:     'Notes Summary',
    tmpl_licensorFeedback: 'Licensor Feedback',
    tmpl_linksSection:     '🔗 Links & Images',
    tmpl_techPackLink:     'Tech Pack Link',
    tmpl_techPackHint:     'Button linking to tech pack URL',
    tmpl_additionalLink:   'Additional Link',
    tmpl_additionalHint:   'Any secondary link on the record',
    tmpl_productImages:    'Product Images',
    tmpl_productImagesHint:'Uploaded photos attached to the record',
    tmpl_save:             'Save Template',
    tmpl_saving:           'Saving…',
    tmpl_saved:            '✓ Saved!',
    tmpl_reset:            'Reset to Default',
    tmpl_resetConfirm:     'Reset this stage to default template?',
    tmpl_noCustom:         'No custom template set — using defaults. Save to activate.',

    // Team / Profile view
    team_title:            'Team & Access',
    team_activeMembers:    'active members',
    team_invite:           'Invite Team Member',
    team_inviteHint:       "They'll receive an email invitation to set their password and join CodiFlow.",
    team_fullName:         'Full Name',
    team_workEmail:        'Work Email',
    team_role:             'Role',
    team_sending:          'Sending…',
    team_sendInvite:       '✉ Send Invite',
    team_errorDomain:      'Must be @cottondivision.com',
    team_errorName:        'Name is required',
    team_active:           'Active',
    team_disabled:         'Disabled',
    team_permissions:      '⚙ Permissions',
    team_quickSet:         'Quick set:',
    team_empty:            'No team members yet. Invite someone above.',
    team_joined:           'Joined',
    team_removeConfirm:    'Remove this team member? They will lose access immediately.',
    team_loading:          'Loading team…',
    team_custom:           'Custom',
    profile_title:         'My Profile',
    profile_myPerms:       'My Permissions',
    profile_directory:     'Team Directory',
  },

  fr: {
    // Nav
    nav_navigate:    'Navigation',
    nav_dashboard:   'Tableau de bord',
    nav_board:       'Kanban',
    nav_table:       'Tableau',
    nav_approved:    'Approuvé',
    nav_samples:     'Échantillons',
    nav_team:        'Équipe',
    nav_profile:     'Profil',
    nav_templates:   'Modèles',
    nav_settings:    'Paramètres',
    nav_newRecord:   '+ Nouvel enregistrement',
    nav_signOut:     'Quitter',

    // Record Drawer
    drawer_details:       'Détails',
    drawer_comments:      'Commentaires',
    drawer_history:       'Historique',
    drawer_edit:          '✏️ Modifier',
    drawer_notify:        '✉ Notifier',
    drawer_archive:       '📁 Archiver',
    drawer_restore:       '📤 Restaurer',
    drawer_archived:      '📁 Archivé',
    drawer_moveStage:     'CHANGER DE STADE',
    drawer_priority:      'PRIORITÉ',
    drawer_waitingOn:     'En attente de :',
    drawer_notes:         'NOTES',
    drawer_feedback:      'RETOUR LICENCIER',
    drawer_attachments:   'PIÈCES JOINTES',
    drawer_upload:        '+ Téléverser',
    drawer_uploading:     'Téléversement…',
    drawer_cover:         'COUVERTURE',
    drawer_setCover:      '⭐ Couverture',
    drawer_open:          'Ouvrir ↗',
    drawer_addComment:    'Ajouter un commentaire…',
    drawer_post:          'Publier',
    drawer_noComments:    'Aucun commentaire pour l\'instant.',
    drawer_noHistory:     'Aucun historique pour l\'instant.',
    drawer_brand:         'Marque',
    drawer_property:      'Propriété',
    drawer_productType:   'Type de produit',
    drawer_gender:        'Genre',
    drawer_owner:         'Propriétaire',
    drawer_contact:       'Contact',
    drawer_licensorRef:   'Réf. Licencier',
    drawer_samples:       'Échantillons',
    drawer_submission:    'Soumission',
    drawer_conceptApproval: 'Approbation concept',
    drawer_ppsPhotos:     'Photos PPS',
    drawer_ppsApproval:   'Approbation PPS',
    drawer_sampleSent:    'Échantillon envoyé',
    drawer_sampleApproval:'Approbation échantillon',
    drawer_techPack:      'Fiche technique',
    drawer_additionalLink:'Lien supplémentaire',
    drawer_deleteConfirm: 'Supprimer cet enregistrement ? Cette action est irréversible.',
    drawer_system:        'Système',

    // Record Form
    form_internalRef:     'Référence interne *',
    form_licensorRef:     'Réf. licencier principale',
    form_productName:     'Nom du produit *',
    form_productType:     'Type de produit',
    form_gender:          'Genre',
    form_brand:           'Marque',
    form_property:        'Propriété',
    form_stage:           'Stade',
    form_priority:        'Priorité',
    form_owner:           'Propriétaire',
    form_waitingOn:       'En attente de',
    form_contact:         'Contact',
    form_nextAction:      'Prochaine action',
    form_notes:           'Notes',
    form_feedback:        'Retour du licencier',
    form_techPackLink:    'Lien fiche technique',
    form_additionalLink:  'Lien supplémentaire',
    form_submissionDate:  'Date de soumission',
    form_samplesQty:      'Qté d\'échantillons',
    form_reminder:        '🔔 Rappel de suivi',
    form_reminderDate:    'Date de rappel',
    form_reminderNote:    'Note (optionnelle)',
    form_reminderDone:    'Marquer le rappel comme terminé',
    form_unassigned:      '— Non assigné —',
    form_select:          '— Sélectionner —',
    form_addBrand:        '＋ Ajouter une marque…',
    form_addProperty:     '＋ Ajouter une propriété…',
    form_typeBrand:       'Entrer le nom de la marque…',
    form_typeProperty:    'Entrer le nom de la propriété…',
    form_reminderPlaceholder: 'ex. Relancer le licencier pour approbation',
    form_attachClick:     'Cliquez pour joindre des images ou fichiers',
    form_attachSub:       'Sera téléversé lors de la sauvegarde',
    form_attachments:     'PIÈCES JOINTES',
    form_uploadFile:      '＋ Joindre un fichier',
    form_uploading:       'Téléversement…',
    form_save:            'Enregistrer',
    form_saving:          'Enregistrement…',
    form_cancel:          'Annuler',

    // Dashboard
    dash_activeRecords:   'Dossiers actifs',
    dash_fullyApproved:   'Entièrement approuvés',
    dash_remindersDue:    'Rappels dus',
    dash_upcomingWeek:    'à venir cette semaine',
    dash_noUpcoming:      'Aucun rappel à venir',
    dash_awaitingLicensor:'En attente du licencier',
    dash_awaitingFull:    'en attente d\'approbation',
    dash_overdue:         '🔴 En retard',
    dash_dueToday:        '🟡 Pour aujourd\'hui',
    dash_upcoming:        '🔵 Prochains (7 jours)',
    dash_reminders:       '🔔 Rappels',
    dash_pending:         'en attente',
    dash_viewAll:         'Voir tout →',
    dash_markDone:        'Marquer fait',
    dash_pipeline:        'Progression du pipeline',
    dash_records:         'dossiers',
    dash_recentActivity:  'Activité récente',
    dash_noActivity:      'Aucune activité récente.',

    // Table
    table_img:            'IMG',
    table_ref:            'Réf',
    table_product:        'Produit',
    table_type:           'Type',
    table_brand:          'Marque',
    table_property:       'Propriété',
    table_stage:          'Stade',
    table_priority:       'Priorité',
    table_owner:          'Propriétaire',
    table_waiting:        'En attente',
    table_nextAction:     'Prochaine action',
    table_samples:        'Échantillons',
    table_reminder:       'Rappel',
    table_noRecords:      'Aucun dossier ne correspond aux filtres.',
    table_search:         'Rechercher…',
    table_allBrands:      'Toutes les marques',
    table_allProperties:  'Toutes les propriétés',
    table_allStages:      'Tous les stades',
    table_allOwners:      'Tous les propriétaires',
    table_allPriorities:  'Toutes les priorités',
    table_waitingOn:      'En attente de',
    table_showArchived:   'Archivés',
    table_showReminders:  'Rappels',
    table_exportCSV:      'Exporter CSV',
    table_newRecord:      '+ Nouveau dossier',

    // Settings
    settings_title:       'Paramètres système',
    settings_subtitle:    'Contrôles réservés aux administrateurs.',
    settings_emailAuto:   'Automatisation des e-mails',
    settings_loading:     'Chargement…',
    settings_reminderLabel: 'E-mails de rappel quotidiens',
    settings_reminderHint:  'Envoyer des rappels automatiques aux propriétaires de dossiers à 9h00 chaque jour pour les rappels dus ou en retard.',
    settings_on:          'Activé',
    settings_off:         'Désactivé',
    settings_howTitle:    'Comment ça fonctionne :',
    settings_howText:     'Chaque jour à 9h00, CodiFlow vérifie les dossiers dont la date de rappel est arrivée ou dépassée. Chaque propriétaire reçoit un e-mail individuel. Désactivez pour stopper tous les e-mails automatiques de rappel.',
    settings_save:        'Enregistrer',
    settings_saving:      'Enregistrement…',
    settings_saved:       '✓ Enregistré !',

    // Dashboard extra
    dash_title:            'Tableau de bord',
    dash_pipelineByStage:  'Pipeline par stade',
    dash_byBrand:          'Dossiers par marque',
    dash_byOwner:          'Dossiers par propriétaire',
    dash_byPriority:       'Par priorité',
    dash_needsAttention:   '⚠️ Nécessite attention',
    dash_allUpToDate:      'Tous les dossiers sont à jour ! ✅',
    dash_noRecords:        'Aucun dossier pour l\'instant.',
    dash_nothingBlocked:   'Rien de bloqué. ✅',
    dash_followUpReminders:'🔔 Rappels de suivi',
    dash_urgentHigh:       'Urgent / Priorité haute',
    dash_urgentCount:      'urgent',
    dash_noUrgent:         'Aucun élément urgent',
    dash_archived:         'archivés',
    dash_withSamples:      'avec échantillons',
    dash_stale:            'inactif',
    dash_waitingOn:        'En attente de',
    dash_staleTag:         'j inactif',

    // Filter bar
    filter_search:         'Rechercher…',
    filter_clearAll:       'Tout effacer',
    filter_archived:       'Archivés',
    filter_allBrands:      'Toutes les marques',
    filter_allProperties:  'Toutes les propriétés',
    filter_allStages:      'Tous les stades',
    filter_allOwners:      'Tous les propriétaires',
    filter_allPriorities:  'Toutes les priorités',
    filter_allWaiting:     'Toutes les attentes',
    filter_reminders:      '🔔 Rappels',

    // Approved view
    approved_title:        '🏆 Designs approuvés',
    approved_subtitle:     'entièrement approuvés · prêts au lancement',
    approved_export:       '↓ Exporter CSV',
    approved_licensorRef:  'Réf. licencier',
    approved_product:      'Produit',
    approved_brandProp:    'Marque / Propriété',
    approved_owner:        'Propriétaire',
    approved_samples:      'Échantillons',
    approved_notes:        'Notes',
    approved_empty:        'Aucun design approuvé pour l\'instant.',

    // Samples view
    samples_title:         '🧪 Demandes d\'échantillons',
    samples_search:        'Rechercher…',
    samples_count:         'dossiers avec échantillons',
    samples_product:       'Produit',
    samples_ref:           'Réf',
    samples_brandProp:     'Marque / Propriété',
    samples_stage:         'Stade',
    samples_owner:         'Propriétaire',
    samples_nextAction:    'Prochaine action',
    samples_qty:           'Qté échantillons',

    // Templates view
    tmpl_title:            '✉ Modèles d\'e-mails',
    tmpl_subtitle:         'Un modèle par stade',
    tmpl_customActive:     'Modèle personnalisé actif',
    tmpl_subjectLine:      'Objet',
    tmpl_subjectPrefix:    'Préfixe d\'objet personnalisé',
    tmpl_optional:         '(optionnel)',
    tmpl_preview:          'Aperçu :',
    tmpl_introMessage:     'Message d\'introduction',
    tmpl_introHint:        'Texte personnalisé (apparaît en haut de l\'e-mail)',
    tmpl_autoSend:         '⚡ Destinataires automatiques',
    tmpl_selectedCount:    'sélectionné(s)',
    tmpl_autoSendHint:     'Les utilisateurs sélectionnés reçoivent automatiquement cet e-mail lorsqu\'un dossier passe à',
    tmpl_noManual:         'Aucune action manuelle requise.',
    tmpl_noTeam:           'Aucun membre actif trouvé.',
    tmpl_willReceive:      'Recevra ✓',
    tmpl_autoNote1:        'utilisateur(s) recevront automatiquement cet e-mail pour chaque changement de stade vers',
    tmpl_emailContent:     'Contenu de l\'e-mail',
    tmpl_emailContentHint: 'Choisissez les champs à inclure dans l\'e-mail pour ce stade.',
    tmpl_productDetails:   '📋 Détails du produit',
    tmpl_licensorRef:      'Référence du licencier',
    tmpl_licensorRefHint:  'Le numéro de référence propre au licencier',
    tmpl_productType:      'Type de produit',
    tmpl_productTypeHint:  'ex. Vêtements, Accessoires',
    tmpl_genderTarget:     'Genre / Cible',
    tmpl_genderTargetHint: 'ex. Unisexe, Garçons',
    tmpl_contactName:      'Nom du contact',
    tmpl_submissionDate:   'Date de soumission',
    tmpl_priorityLevel:    'Niveau de priorité',
    tmpl_priorityHint:     'Bas / Moyen / Élevé / Urgent',
    tmpl_samplesQty:       'Quantité d\'échantillons',
    tmpl_workflow:         '⚡ État du flux de travail',
    tmpl_waitingOn:        'En attente de',
    tmpl_waitingOnHint:    'Qui bloque actuellement la progression',
    tmpl_nextAction:       'Prochaine action',
    tmpl_nextActionHint:   'Ce qui doit se passer ensuite',
    tmpl_notesSection:     '📝 Notes & Retours',
    tmpl_notesSummary:     'Résumé des notes',
    tmpl_licensorFeedback: 'Retour du licencier',
    tmpl_linksSection:     '🔗 Liens & Images',
    tmpl_techPackLink:     'Lien fiche technique',
    tmpl_techPackHint:     'Bouton vers l\'URL de la fiche technique',
    tmpl_additionalLink:   'Lien supplémentaire',
    tmpl_additionalHint:   'Tout lien secondaire du dossier',
    tmpl_productImages:    'Images produit',
    tmpl_productImagesHint:'Photos téléchargées attachées au dossier',
    tmpl_save:             'Enregistrer le modèle',
    tmpl_saving:           'Enregistrement…',
    tmpl_saved:            '✓ Enregistré !',
    tmpl_reset:            'Réinitialiser',
    tmpl_resetConfirm:     'Réinitialiser ce stade au modèle par défaut ?',
    tmpl_noCustom:         'Aucun modèle personnalisé — valeurs par défaut utilisées. Enregistrez pour activer.',

    // Team / Profile view
    team_title:            'Équipe & Accès',
    team_activeMembers:    'membres actifs',
    team_invite:           'Inviter un membre',
    team_inviteHint:       'Ils recevront une invitation par e-mail pour définir leur mot de passe et rejoindre CodiFlow.',
    team_fullName:         'Nom complet',
    team_workEmail:        'E-mail professionnel',
    team_role:             'Rôle',
    team_sending:          'Envoi…',
    team_sendInvite:       '✉ Envoyer l\'invitation',
    team_errorDomain:      'Doit être @cottondivision.com',
    team_errorName:        'Le nom est obligatoire',
    team_active:           'Actif',
    team_disabled:         'Désactivé',
    team_permissions:      '⚙ Permissions',
    team_quickSet:         'Définir rapidement :',
    team_empty:            'Aucun membre pour l\'instant. Invitez quelqu\'un ci-dessus.',
    team_joined:           'Rejoint le',
    team_removeConfirm:    'Supprimer ce membre ? Il perdra l\'accès immédiatement.',
    team_loading:          'Chargement de l\'équipe…',
    team_custom:           'Personnalisé',
    profile_title:         'Mon profil',
    profile_myPerms:       'Mes permissions',
    profile_directory:     'Annuaire équipe',
  },
}

export type Translations = typeof T['en']

// ── Stage name translations (display only — DB values stay in English) ─────────
const STAGE_LABELS_FR: Record<string, string> = {
  'Design Sent':                   'Design envoyé',
  'Modifications Requested':       'Modifications demandées',
  'Concept Approved':              'Concept approuvé',
  'PreProduction Samples PPS':     'Échantillons préproduction',
  'PPS Shipped':                   'PPS expédié',
  'Proceed to Production':         'Passer en production',
  'Production Samples':            'Échantillons production',
  'Production Samples Shipped':    'Échantillons expédiés',
  'Fully Approved':                'Entièrement approuvé',
  'Archived':                      'Archivé',
}

// ── Context ────────────────────────────────────────────────────────────────────
interface LangCtx { lang: Lang; setLang: (l: Lang) => void; t: Translations }
const Ctx = createContext<LangCtx>({ lang: 'en', setLang: () => {}, t: T.en })

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  useEffect(() => {
    const stored = localStorage.getItem('codi_lang') as Lang | null
    if (stored === 'en' || stored === 'fr') setLangState(stored)
  }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('codi_lang', l)
  }

  return <Ctx.Provider value={{ lang, setLang, t: T[lang] }}>{children}</Ctx.Provider>
}

export function useLanguage() {
  const ctx = useContext(Ctx)
  /** Returns the display label for a stage name in the current language */
  function stageLabel(stage: string): string {
    if (ctx.lang === 'fr') return STAGE_LABELS_FR[stage] ?? stage
    return stage
  }
  return { ...ctx, stageLabel }
}
